# Rest api testing; requires REST Client extention installed
@host=http://localhost:3000/api

###
POST {{host}}/users/login HTTP/1.1
content-type: application/json

{
    "user": {
        "email": "damien@test.com",
        "password": "password"
    }
}

###
GET {{host}}/me HTTP/1.1


###

POST {{host}}/patients HTTP/1.1
content-type: application/json

{
    "patient": {
        "name": "new paaa",
        "email": "newpaaa@gmail.com",
        "gender": "female",
        "phone": "021000000"
    }
}

###
GET {{host}}/patients HTTP/1.1
